### ISSUE TITLE
After upgrading from @inlang/cli v3.3.0 to v3.3.1 or v3.3.2, the CI pipeline fails

### ISSUE THREAD

**Issue by fr33bits** [opral/inlang-cli#32]
I use the NPM script `inlang validate --project ./project.inlang` instead of `npx @inlang/cli  validate --project ./project.inlang` but that has worked before the upgrade and using the latter in the GitLab CI pipeline leads to the same outcome. Meanwhile, locally on my Windows 11 machine, the script runs fine and does not error out.

After upgrading from v3.3.0 to v3.3.2, the CI pipeline gives the following error:

```
$ npm run validate:int
> my-project-2@0.1.0 validate:int
> inlang validate --project ./project.inlang
[info] 🔎 Validating the inlang project...
Error opening inlang project at ./project.inlang Error: Cannot find module '/builds/my-projects/my-project-2/node_modules/@inlang/cli/dist/entry.node.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1517:15)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1071:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1095:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1122:12)
    at Module._load (node:internal/modules/cjs/loader:1294:5)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:223:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:856:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

While trying to troubleshoot with ChatGPT, I think I may have identified a possible culprit. Within `node_modules\@inlang\cli\dist\main.js` (which is imported by `node_modules\@inlang\cli\bin\run.js`), the following code:

```js
// ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/worker/factory.node.js
import { Worker as Worker2 } from "node:worker_threads";
function createWorkerConnection() {
  const worker = new Worker2(new URL("./entry.node.js", import.meta.url), {
    name: "lix"
  });
```

calls `./entry.node.js`, when I think it should be calling `./main.js`. This seems to be a result of the Lix library being incorporated into this code.

If I upgrade from v3.3.0 to v3.3.1, I get a different error:

```
$ npm run validate:int
> my-project-2@0.1.0 validate:int
> inlang validate --project ./project.inlang
[info] 🔎 Validating the inlang project...
Error opening inlang project at ./project.inlang Error: Failed to load @lix-js/sdk native addon for linux-x64. This package requires the matching optional native binary package. Run `npm run build` from packages/js-sdk for local development, or install a release that includes your platform binary.
    at ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/binding.node.js (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:6777:21)
    at __init (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:28:56)
    at ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/worker/factory.node.js (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:6824:5)
    at __init (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:28:56)
    at ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/worker/client.js (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:6989:5)
    at __init (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:28:56)
    at file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:30467:95
    at async openLix (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:30467:59)
    at async newProject (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:46193:15)
    at async loadProjectFromDirectory (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:47478:18) {
  cause: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /builds/myprojects/my-project-2/node_modules/@lix-js/sdk-linux-x64/lix_js_sdk.node)
      at Object..node (node:internal/modules/cjs/loader:2030:18)
      at Module.load (node:internal/modules/cjs/loader:1594:32)
      at Module._load (node:internal/modules/cjs/loader:1396:12)
      at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
      at Module.require (node:internal/modules/cjs/loader:1617:12)
      at require (node:internal/modules/helpers:153:16)
      at ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/binding.node.js (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:6775:15)
      at __init (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:28:56)
      at ../../node_modules/.pnpm/@lix-js+sdk@0.12.0/node_modules/@lix-js/sdk/dist/worker/factory.node.js (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:6824:5)
      at __init (file:///builds/myprojects/my-project-2/node_modules/@inlang/cli/dist/main.js:28:56) {
    code: 'ERR_DLOPEN_FAILED'
  }
}
```

Even after the `npm i -D @lix-js/sdk` install, the same error is present, though I don't think installing a separate SDK should be necessary here at all anyway.

Additionally, it might be a good idea to add tests to ensure that this command or the pipeline does not break between version upgrades as this has happened many times now.
